### ISSUE TITLE
OpenMP on Mac

### ISSUE THREAD

**Issue by philstopford** [NiklasRosenstein/c4d-aaOcean#3]
You should be able to use OpenMP on Mac without too much trouble. You can install llvm from homebrew and use that compiler instead with the -fopenmp switch in 'OTHER_CFLAGS'. A similar set-up is in place in the aaOcean for MODO project here : https://github.com/philstopford/aaOcean_MODO.

**Comment by NiklasRosenstein** [comment]
The v1.0.1 R20 builds use OpenMP on OSX via `libomp` from Homebrew.

https://github.com/NiklasRosenstein/c4d-aaOcean/releases/tag/v1.0.1
